language: ruby
rvm:
  - 2.2.1
sudo: false
addons:
  postgresql: 9.3
env:
  - DATABASE_URL=postgres://localhost/stash_api_test
before_script:
  - date
  - psql -c 'create database stash_api_test;' -U postgres
  - bin/setup
script:
  - bundle exec rake
