db:
  image: postgres
  ports:
    - "5432"
web:
  build: .
  environment: 
    RACK_ENV: development
    DATABASE_URL: postgres://postgres@db/stash_api_development
    TZ: UTC
    FORCE_SSL: FALSE
    VERSIONING_DEFAULT: 1
    VERSIONING_APP_NAME: stash
    RAISE_ERRORS: true
  command: bundle exec puma --config config/puma.rb config.ru 
  volumes:
    - .:/app
  ports: 
    - "5000:5000"
  links:
    - db
