db:
  image: postgres
  ports:
    - "5432"
redis:
  image: redis
  ports:
    - "6379"
web:
  build: .
  command: bundle exec foreman start -e .env.docker
  ports: 
    - "5000:5000"
  volumes:
    - .:/myapp
  links:
    - db
    - redis
